src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CaseRelatedTo__c</fullName>
        <label>CaseRelatedTo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Product Support</fullName>
                </value>
                <value>
                    <fullName>Hardware Support</fullName>
                </value>
                <value>
                    <fullName>Software Support</fullName>
                </value>
                <value>
                    <fullName>Technical Expertise</fullName>
                </value>
                <value>
                    <fullName>Inquiry</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Case_User__c.object
<CustomObject>
    <fields>
        <fullName>Availability__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Availability</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AvailableUsers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AvailableUsers</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Case_Allocated_Time__c</fullName>
        <label>Last Case Allocated Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SkillSet__c</fullName>
        <label>SkillSet</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Product Support</fullName>
                </value>
                <value>
                    <fullName>Hardware Support</fullName>
                </value>
                <value>
                    <fullName>Software Support</fullName>
                </value>
                <value>
                    <fullName>Technical Expertise</fullName>
                </value>
                <value>
                    <fullName>Inquiry</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Timings__c</fullName>
        <label>Timings</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>6:00AM-3:00PM</fullName>
                </value>
                <value>
                    <fullName>9:00AM-6:00PM</fullName>
                </value>
                <value>
                    <fullName>2:00PM-11:00PM</fullName>
                </value>
                <value>
                    <fullName>6:00PM-3:00AM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case User</label>
    <nameField>
        <label>CaseUser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CaseAllocation.cls
public class CaseAllocation{

   public static void caseAssign(Case[] cas){
   List<ID> cIds = new List<ID>();
       
    List<Case_User__c> cuser = New  List<Case_User__c>();
    Map<ID, Case_User__c> cusermap = new Map<ID, Case_User__c>();

    Set<String> skillSet = new Set<String>();
    List<String> skillSetList = new List<String>();
    
    for(Case c : cas){
        
        if(c.Status == 'New') {
            cIds.add(c.Id); //add case ids.
        }     
        skillSet.add(c.CaseRelatedTo__c); 
     }   
     skillSetList.addAll(skillSet);    
   
     try{
     
         //available users               
         List<Case> cases = new List<Case>();
         List<Case_User__c> availableCaseUsers = [SELECT AvailableUsers__c, Timings__c, SkillSet__c FROM Case_User__c where Availability__c = TRUE ORDER BY Last_Case_Allocated_Time__c ASC];
         //List<Case_User__c> availableCaseUsers = Database.query(queryString);
         integer i=0;
         integer nomatchingSkillset = availableCaseUsers.size();
         for(Case c: cases){
             for(; i<=availableCaseUsers.size();i++){
                if(availableCaseUsers.get(i).SkillSet__c.contains(c.CaseRelatedTo__c)){
                  c.OwnerId = availableCaseUsers.get(i).AvailableUsers__c;
                  availableCaseUsers.get(i).Last_Case_Allocated_Time__c = DateTime.now();
                  cusermap.put(availableCaseUsers.get(i).id, availableCaseUsers.get(i));
                } else {
                      nomatchingSkillset--;
                      if(nomatchingSkillset == 0){
                          //TODO assign to case queue
                          
                          break;
                      }
                      continue; 
                }
                if(i>=availableCaseUsers.size()){
                    i=0;
                }
                break;
             }      
         }
        }catch(System.DmlException e){
        
             System.debug('Missing the required field in record');
             
        }catch(Exception e){
        
             System.debug('An Error Occured at:' +e.getMessage());
             
        }finally{
        
             System.debug('This is block just for closing the class');
        }
      
  
     if(!cusermap.isEmpty()) {
      update cusermap.values();
     }
        
   
   }

}