src/objects/Incident__c.object
<CustomObject>
    <fields>
        <fullName>Incident_Fields__c</fullName>
        <label>Incident Fields</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incident State</fullName>
                </value>
                <value>
                    <fullName>Impact</fullName>
                </value>
                <value>
                    <fullName>Status</fullName>
                </value>
                <value>
                    <fullName>Short Description</fullName>
                </value>
                <value>
                    <fullName>Sys ID</fullName>
                </value>
                <value>
                    <fullName>Contact Type</fullName>
                </value>
                <value>
                    <fullName>Sys Updated On</fullName>
                </value>
                <value>
                    <fullName>u_sftype</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Now Incident</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Incident Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Sample.cls
public class Sample{
public Sample(ApexPages.standardController stdcontroller){}

public List<Selectoption> getCommpref()
    {
        List<SelectOption> Commprefvalue = new List<SelectOption>();
        Schema.DescribeFieldResult CommprefField = Schema.sObjectType.Incident__c.fields.Incident_Fields__c; 
        Schema.PicklistEntry [] Commpref = CommprefField.getPickListValues();
        //Schema.PicklistEntry [] values = vendorField.getPickListValues();
        for(Schema.PicklistEntry val : Commpref)
        {
            Commprefvalue.add(new SelectOption(val.getValue(), val.getLabel()));
        }
        return Commprefvalue;        
    }
    }