src/objects/Incident__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Incidents</relationshipLabel>
        <relationshipName>Incidents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident_Fields__c</fullName>
        <label>Incident Fields</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incident State</fullName>
                </value>
                <value>
                    <fullName>Impact</fullName>
                </value>
                <value>
                    <fullName>Status</fullName>
                </value>
                <value>
                    <fullName>Short Description</fullName>
                </value>
                <value>
                    <fullName>Sys ID</fullName>
                </value>
                <value>
                    <fullName>Contact Type</fullName>
                </value>
                <value>
                    <fullName>Sys Updated On</fullName>
                </value>
                <value>
                    <fullName>u_sftype</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Now Incident</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Incident Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CaseFieldsGet.cls
public with sharing class CaseFieldsGet {
	
	//global Incident__c ic {get;set;}
    
    public void IncidentFields(){
    Map<ID, Incident__c> inMap = new Map<ID, Incident__c>();
      
    Incident__c inc = [Select Incident_Fields__c From Incident__c Where Account__r.Name='ABC Heights' Limit 1];
        
      
        String[] incFields = inc.Incident_Fields__c.split(';');
        
       // for(String s ; s<=incFields.size(); s++)
        
    }  
		 
   // List<SelectOption> options = new List<SelectOption>(); 
	
	public CaseFieldsGet(Apexpages.standardController c){}
	
	 public void caseFields(){
	  	
	  	   Schema.DescribeSObjectResult objSchema =  Case.sObjectType.getDescribe();       
           Map<String, Schema.SObjectField> fieldMap = objSchema.fields.getMap();
                      
           System.debug('casefield::'+ fieldMap);
	 }
    
}