src/objects/JiraIssues__c.object
<CustomObject>
    <fields>
        <fullName>issuetype__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Issuetype</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>priority__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Priority</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>summary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Summary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>updated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Updated</label>
        <type>Checkbox</type>
    </fields>
    <label>JiraIssues</label>
    <nameField>
        <displayFormat>JI-{0000}</displayFormat>
        <label>JiraIssues Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JiraIssues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/JiraFieldsController.cls
public with sharing class JiraFieldsController {

    public String fields { get; set; }
    
     public Boolean issuetype {get;set;} 
     public Boolean priority {get;set;} 
     public Boolean status {get;set;}      
     public Boolean summary {get;set;} 
     public Boolean updated {get;set;}     

     //List<JiraIssues__c>  jiList = new List<JiraIssues__c>();
     
     public PageReference doInsert() {
        
           JiraIssues__c jIssue = new JiraIssues__c();   
               
           jIssue.issuetype__c = issuetype ;       
           jIssue.priority__c = priority ;      
           jIssue.status__c = status;        
           jIssue.summary__c = summary;       
           jIssue.updated__c = updated;
                     
           insert jIssue;         
      
                    
           Schema.DescribeSObjectResult objSchema = JiraIssues__c.sObjectType.getDescribe();       
           Map<String, Schema.SObjectField> fieldMap = objSchema.fields.getMap();
        
           //Set<String> fields = new Set<String>(); 
           String [] fields = new List<String>();
        
           for (String fieldName : fieldMap.keySet()){
            
               SObjectField sfield = fieldMap.get(fieldName);
            
               schema.describefieldresult dfield = sfield.getDescribe();
               if(jIssue.get(fieldName) == true) {
                   if(dfield.isCustom() && String.valueOf(dfield.getSoapType()) == 'Boolean') {
                      system.debug(jIssue.get(fieldName));
                      fields.add(fieldName);
                      System.debug('All Fields are selected ::::'+fieldName);
                   }  
               }
           }                                       
       
           PageReference Page = new PageReference('https://c.na40.visual.force.com/apex/JiraSelectedFields');
           Page.setRedirect(true);   
           return Page;
        
     }      
             
}